const isWeapp = process.env.TARO_ENV === 'weapp'

const weappPages = [
  'pages-weapp/home/index',
  'pages-weapp/detail/index',
  'pages-weapp/checkout/index',
  'pages-weapp/success/index',
  'pages-weapp/my-leases/index',
  'pages-weapp/profile/index',
  'pages-weapp/login/index',
  'pages-weapp/profile-complete/index',
  'pages-weapp/membership/index',
  'pages-weapp/bind/index',
  'pages-weapp/profile/edit/index',
  'pages-weapp/order-detail/index',
  'pages-weapp/search/index',
  'pages-weapp/payment/index',
  'pages-weapp/renewal/index',
]

const h5Pages = [
  'pages/home/index',
  'pages/detail/index',
  'pages/booking/index',
  'pages/cart/index',
  'pages/create-repair/index',
  'pages/checkout/index',
  'pages/lease-history/index',
  'pages/maintenance-progress/index',
  'pages/membership/index',
  'pages/message-detail/index',
  'pages/messages/index',
  'pages/my-contracts/index',
  'pages/my-leases/index',
  'pages/my-repairs/index',
  'pages/my-service/index',
  'pages/order-detail/index',
  'pages/payment-complete/index',
  'pages/profile/index',
  'pages/receive-confirm/index',
  'pages/receiving-interface/index',
  'pages/receiving-repair-scan/index',
  'pages/repair/index',
  'pages/repair-quote/index',
  'pages/repair-request/index',
  'pages/repair-scan/index',
  'pages/return-confirm/index',
  'pages/shipping-interface/index',
  'pages/site-detail/index',
  'pages/success/index',
  'pages/staff-instrument-detail/index',
  'pages/staff-instrument-form/index',
  'pages/staff-instruments/index',
  'pages/staff-order-detail/index',
  'pages/staff-orders/index',
  'pages/staff-receive-confirm/index',
  'pages/transit-workflow/index',
  'pages/user-warnings/index',
]

export default {
  pages: isWeapp ? weappPages : h5Pages,
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'TuneLoop',
    navigationBarTextStyle: 'black',
  },
}
