export default {
  pages: [
    'pages/home/index',
    'pages/detail/index',
    'pages/booking/index',
    'pages/cart/index',
    'pages/checkout/index',
    'pages/lease-history/index',
    'pages/maintenance-progress/index',
    'pages/membership/index',
    'pages/message-detail/index',
    'pages/messages/index',
    'pages/my-contracts/index',
    'pages/my-leases/index',
    'pages/my-repairs/index',
    'pages/my-service/index',
    'pages/order-detail/index',
    'pages/payment-complete/index',
    'pages/profile/index',
    'pages/receive-confirm/index',
    'pages/receiving-interface/index',
    'pages/repair-scan/index',
    'pages/return-confirm/index',
    'pages/shipping-interface/index',
    'pages/site-detail/index',
    'pages/success/index',
    'pages/staff-instrument-detail/index',
    'pages/staff-instrument-form/index',
    'pages/staff-instruments/index',
    'pages/staff-order-detail/index',
    'pages/staff-orders/index',
    'pages/staff-receive-confirm/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'TuneLoop',
    navigationBarTextStyle: 'black',
  },
}
