const isWeapp = process.env.TARO_ENV === 'weapp'

const weappPages = [
  'pages-weapp/home/index',
  'pages-weapp/detail/index',
  'pages-weapp/checkout/index',
  'pages-weapp/success/index',
  'pages-weapp/my-leases/index',
  'pages-weapp/mall/index',
  'pages-weapp/profile/index',
  'pages-weapp/login/index',
  'pages-weapp/profile-complete/index',
  'pages-weapp/membership/index',
  'pages-weapp/bind/index',
  'pages-weapp/profile/edit/index',
  'pages-weapp/order-detail/index',
  'pages-weapp/search/index',
  'pages-weapp/payment/index',
  'pages-weapp/renewal/index',
  'pages-weapp/content/index',
  'pages-weapp/setting/index',
  'pages-weapp/return-settlement/index',
  'pages-weapp/messages/index',
  'pages-weapp/message-detail/index',
  'pages-weapp/shipping-interface/index',
  'pages-weapp/receiving-interface/index',
  'pages-weapp/staff-receive-confirm/index',
  'pages-weapp/transit-workbench/index',
  'pages-weapp/transit-receive/index',
  'pages-weapp/transit-ship/index',
  'pages-weapp/staff-orders/index',
  'pages-weapp/cart/index',
  'pages-weapp/my-repairs/index',
  'pages-weapp/receive-confirm/index',
  'pages-weapp/return-confirm/index',
  'pages-weapp/account-select/index',
  'pages-weapp/staff-instruments/index',
  'pages-weapp/staff-instrument-detail/index',
  'pages-weapp/staff-instrument-form/index',
  'pages-weapp/repair/index',
  'pages-weapp/repair-request/index',
  'pages-weapp/repair-quote/index',
  'pages-weapp/payment-complete/index',
  'pages-weapp/repair-payment-complete/index',
  'pages-weapp/receiving-repair-scan/index',
  'pages-weapp/repair-scan/index',
  'pages-weapp/tech-repair-workbench/index',
  'pages-weapp/repair-service-create/index',
  'pages-weapp/repair-service-detail/index',
  'pages-weapp/instrument-loss-manage/index',
  'pages-weapp/tech-detail/index',
  'pages-weapp/tech-list/index',
  'pages-weapp/invoice/index',
  'pages-weapp/face-verify/index',
  'pages-weapp/about/index',
]

const h5Pages = [
  'pages/home/index',
  'pages/detail/index',
  'pages/cart/index',
  'pages/checkout/index',
  'pages/membership/index',
  'pages/message-detail/index',
  'pages/messages/index',
  'pages/my-leases/index',
  'pages/mall/index',
  'pages/my-repairs/index',
  'pages/order-detail/index',
  'pages/payment-complete/index',
  'pages/profile/index',
  'pages/receive-confirm/index',
  'pages/transit-workbench/index',
  'pages/transit-receive/index',
  'pages/transit-ship/index',
  'pages/receiving-interface/index',
  'pages/receiving-repair-scan/index',
  'pages/tech-repair-workbench/index',
  'pages/repair-service-create/index',
  'pages/repair-service-detail/index',
  'pages/instrument-loss-manage/index',
  'pages/tech-detail/index',
  'pages/tech-list/index',
  'pages/repair/index',
  'pages/repair-quote/index',
  'pages/repair-request/index',
  'pages/repair-scan/index',
  'pages/return-confirm/index',
  'pages/shipping-interface/index',
  'pages/success/index',
  'pages/staff-instrument-detail/index',
  'pages/staff-instrument-form/index',
  'pages/staff-instruments/index',
  'pages/staff-orders/index',
  'pages/staff-receive-confirm/index',
  'pages/face-verify/index',
  'pages/about/index',
]

// #2175: 底条「租赁」改为「商城」（tabBar 页）；「我的租赁」降为个人中心二级页
// （navigateTo，不再是 tab）。custom:true 隐藏系统 tabBar，由 src 的 BottomNav 渲染。
const tabBar = isWeapp ? {
  custom: true,
  color: '#8a8a8a',
  selectedColor: '#5A3B24',
  backgroundColor: '#5A3B24',
  list: [
    { pagePath: 'pages-weapp/home/index', text: '首页' },
    { pagePath: 'pages-weapp/mall/index', text: '商城' },
    { pagePath: 'pages-weapp/profile/index', text: '我的' },
  ],
} : undefined

export default {
  pages: isWeapp ? weappPages : h5Pages,
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'TuneLoop',
    navigationBarTextStyle: 'black',
    pageOrientation: 'portrait',
  },
  ...(tabBar ? { tabBar } : {}),
}
