ALTER TABLE merchants ADD COLUMN IF NOT EXISTS admin_pending BOOLEAN DEFAULT false;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS manager_pending BOOLEAN DEFAULT false;
ALTER TABLE site_members ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
ALTER TABLE site_members ADD COLUMN IF NOT EXISTS iam_task_id VARCHAR(255);
