ALTER TABLE merchants ADD COLUMN IF NOT EXISTS merchant_type VARCHAR(20) DEFAULT 'full';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS transit_address TEXT DEFAULT '';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS transit_phone VARCHAR(50) DEFAULT '';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS transit_contact_name VARCHAR(255) DEFAULT '';