ALTER TABLE users ADD COLUMN IF NOT EXISTS membership_level_id INTEGER REFERENCES membership_levels(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_spending DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS prepaid_points DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS promo_points DECIMAL NOT NULL DEFAULT 0;
