-- #1727 P2 down：BIGINT(分) → DECIMAL(10,2)(元)，round 到分位。
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS final_amount_yuan decimal(10,2);
UPDATE appeals SET final_amount_yuan = ROUND(final_amount / 100.0, 2) WHERE final_amount IS NOT NULL;
ALTER TABLE appeals DROP COLUMN IF EXISTS final_amount;
ALTER TABLE appeals RENAME COLUMN final_amount_yuan TO final_amount;
ALTER TABLE damage_reports ADD COLUMN IF NOT EXISTS damage_amount_yuan decimal(10,2);
UPDATE damage_reports SET damage_amount_yuan = ROUND(damage_amount / 100.0, 2) WHERE damage_amount IS NOT NULL;
ALTER TABLE damage_reports DROP COLUMN IF EXISTS damage_amount;
ALTER TABLE damage_reports RENAME COLUMN damage_amount_yuan TO damage_amount;
ALTER TABLE damage_reports ADD COLUMN IF NOT EXISTS deposit_deducted_yuan decimal(10,2);
UPDATE damage_reports SET deposit_deducted_yuan = ROUND(deposit_deducted / 100.0, 2) WHERE deposit_deducted IS NOT NULL;
ALTER TABLE damage_reports DROP COLUMN IF EXISTS deposit_deducted;
ALTER TABLE damage_reports RENAME COLUMN deposit_deducted_yuan TO deposit_deducted;
ALTER TABLE damage_reports ADD COLUMN IF NOT EXISTS overdue_fee_yuan decimal(10,2);
UPDATE damage_reports SET overdue_fee_yuan = ROUND(overdue_fee / 100.0, 2) WHERE overdue_fee IS NOT NULL;
ALTER TABLE damage_reports DROP COLUMN IF EXISTS overdue_fee;
ALTER TABLE damage_reports RENAME COLUMN overdue_fee_yuan TO overdue_fee;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE deposits SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE deposits DROP COLUMN IF EXISTS amount;
ALTER TABLE deposits RENAME COLUMN amount_yuan TO amount;
ALTER TABLE discount_policies ADD COLUMN IF NOT EXISTS max_amount_yuan decimal(10,2);
UPDATE discount_policies SET max_amount_yuan = ROUND(max_amount / 100.0, 2) WHERE max_amount IS NOT NULL;
ALTER TABLE discount_policies DROP COLUMN IF EXISTS max_amount;
ALTER TABLE discount_policies RENAME COLUMN max_amount_yuan TO max_amount;
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS base_daily_rate_yuan decimal(10,2);
UPDATE instruments SET base_daily_rate_yuan = ROUND(base_daily_rate / 100.0, 2) WHERE base_daily_rate IS NOT NULL;
ALTER TABLE instruments DROP COLUMN IF EXISTS base_daily_rate;
ALTER TABLE instruments RENAME COLUMN base_daily_rate_yuan TO base_daily_rate;
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS deposit_yuan decimal(10,2);
UPDATE instruments SET deposit_yuan = ROUND(deposit / 100.0, 2) WHERE deposit IS NOT NULL;
ALTER TABLE instruments DROP COLUMN IF EXISTS deposit;
ALTER TABLE instruments RENAME COLUMN deposit_yuan TO deposit;
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS total_price_yuan decimal(10,2);
UPDATE instruments SET total_price_yuan = ROUND(total_price / 100.0, 2) WHERE total_price IS NOT NULL;
ALTER TABLE instruments DROP COLUMN IF EXISTS total_price;
ALTER TABLE instruments RENAME COLUMN total_price_yuan TO total_price;
ALTER TABLE leases ADD COLUMN IF NOT EXISTS deposit_amount_yuan decimal(10,2);
UPDATE leases SET deposit_amount_yuan = ROUND(deposit_amount / 100.0, 2) WHERE deposit_amount IS NOT NULL;
ALTER TABLE leases DROP COLUMN IF EXISTS deposit_amount;
ALTER TABLE leases RENAME COLUMN deposit_amount_yuan TO deposit_amount;
ALTER TABLE leases ADD COLUMN IF NOT EXISTS monthly_rent_yuan decimal(10,2);
UPDATE leases SET monthly_rent_yuan = ROUND(monthly_rent / 100.0, 2) WHERE monthly_rent IS NOT NULL;
ALTER TABLE leases DROP COLUMN IF EXISTS monthly_rent;
ALTER TABLE leases RENAME COLUMN monthly_rent_yuan TO monthly_rent;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS estimated_cost_yuan decimal(10,2);
UPDATE maintenance_tickets SET estimated_cost_yuan = ROUND(estimated_cost / 100.0, 2) WHERE estimated_cost IS NOT NULL;
ALTER TABLE maintenance_tickets DROP COLUMN IF EXISTS estimated_cost;
ALTER TABLE maintenance_tickets RENAME COLUMN estimated_cost_yuan TO estimated_cost;
ALTER TABLE membership_levels ADD COLUMN IF NOT EXISTS min_amount_yuan decimal(10,2);
UPDATE membership_levels SET min_amount_yuan = ROUND(min_amount / 100.0, 2) WHERE min_amount IS NOT NULL;
ALTER TABLE membership_levels DROP COLUMN IF EXISTS min_amount;
ALTER TABLE membership_levels RENAME COLUMN min_amount_yuan TO min_amount;
ALTER TABLE order_payment_records ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE order_payment_records SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE order_payment_records DROP COLUMN IF EXISTS amount;
ALTER TABLE order_payment_records RENAME COLUMN amount_yuan TO amount;
ALTER TABLE order_refund_records ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE order_refund_records SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE order_refund_records DROP COLUMN IF EXISTS amount;
ALTER TABLE order_refund_records RENAME COLUMN amount_yuan TO amount;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cash_paid_yuan decimal(10,2);
UPDATE orders SET cash_paid_yuan = ROUND(cash_paid / 100.0, 2) WHERE cash_paid IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS cash_paid;
ALTER TABLE orders RENAME COLUMN cash_paid_yuan TO cash_paid;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS deposit_yuan decimal(10,2);
UPDATE orders SET deposit_yuan = ROUND(deposit / 100.0, 2) WHERE deposit IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS deposit;
ALTER TABLE orders RENAME COLUMN deposit_yuan TO deposit;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gift_points_used_yuan decimal(10,2);
UPDATE orders SET gift_points_used_yuan = ROUND(gift_points_used / 100.0, 2) WHERE gift_points_used IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS gift_points_used;
ALTER TABLE orders RENAME COLUMN gift_points_used_yuan TO gift_points_used;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS monthly_rent_yuan decimal(10,2);
UPDATE orders SET monthly_rent_yuan = ROUND(monthly_rent / 100.0, 2) WHERE monthly_rent IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS monthly_rent;
ALTER TABLE orders RENAME COLUMN monthly_rent_yuan TO monthly_rent;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS prepaid_points_used_yuan decimal(10,2);
UPDATE orders SET prepaid_points_used_yuan = ROUND(prepaid_points_used / 100.0, 2) WHERE prepaid_points_used IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS prepaid_points_used;
ALTER TABLE orders RENAME COLUMN prepaid_points_used_yuan TO prepaid_points_used;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_fee_yuan decimal(10,2);
UPDATE orders SET shipping_fee_yuan = ROUND(shipping_fee / 100.0, 2) WHERE shipping_fee IS NOT NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS shipping_fee;
ALTER TABLE orders RENAME COLUMN shipping_fee_yuan TO shipping_fee;
ALTER TABLE overdue_charges ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE overdue_charges SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE overdue_charges DROP COLUMN IF EXISTS amount;
ALTER TABLE overdue_charges RENAME COLUMN amount_yuan TO amount;
ALTER TABLE payment_sessions ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE payment_sessions SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE payment_sessions DROP COLUMN IF EXISTS amount;
ALTER TABLE payment_sessions RENAME COLUMN amount_yuan TO amount;
ALTER TABLE points_transactions ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE points_transactions SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE points_transactions DROP COLUMN IF EXISTS amount;
ALTER TABLE points_transactions RENAME COLUMN amount_yuan TO amount;
ALTER TABLE points_transactions ADD COLUMN IF NOT EXISTS balance_after_prepaid_yuan decimal(10,2);
UPDATE points_transactions SET balance_after_prepaid_yuan = ROUND(balance_after_prepaid / 100.0, 2) WHERE balance_after_prepaid IS NOT NULL;
ALTER TABLE points_transactions DROP COLUMN IF EXISTS balance_after_prepaid;
ALTER TABLE points_transactions RENAME COLUMN balance_after_prepaid_yuan TO balance_after_prepaid;
ALTER TABLE registration_sessions ADD COLUMN IF NOT EXISTS amount_yuan decimal(10,2);
UPDATE registration_sessions SET amount_yuan = ROUND(amount / 100.0, 2) WHERE amount IS NOT NULL;
ALTER TABLE registration_sessions DROP COLUMN IF EXISTS amount;
ALTER TABLE registration_sessions RENAME COLUMN amount_yuan TO amount;
ALTER TABLE repair_quotes ADD COLUMN IF NOT EXISTS logistics_fee_yuan decimal(10,2);
UPDATE repair_quotes SET logistics_fee_yuan = ROUND(logistics_fee / 100.0, 2) WHERE logistics_fee IS NOT NULL;
ALTER TABLE repair_quotes DROP COLUMN IF EXISTS logistics_fee;
ALTER TABLE repair_quotes RENAME COLUMN logistics_fee_yuan TO logistics_fee;
ALTER TABLE repair_quotes ADD COLUMN IF NOT EXISTS material_fee_yuan decimal(10,2);
UPDATE repair_quotes SET material_fee_yuan = ROUND(material_fee / 100.0, 2) WHERE material_fee IS NOT NULL;
ALTER TABLE repair_quotes DROP COLUMN IF EXISTS material_fee;
ALTER TABLE repair_quotes RENAME COLUMN material_fee_yuan TO material_fee;
ALTER TABLE repair_quotes ADD COLUMN IF NOT EXISTS service_fee_yuan decimal(10,2);
UPDATE repair_quotes SET service_fee_yuan = ROUND(service_fee / 100.0, 2) WHERE service_fee IS NOT NULL;
ALTER TABLE repair_quotes DROP COLUMN IF EXISTS service_fee;
ALTER TABLE repair_quotes RENAME COLUMN service_fee_yuan TO service_fee;
ALTER TABLE repair_requests ADD COLUMN IF NOT EXISTS check_fee_snapshot_yuan decimal(10,2);
UPDATE repair_requests SET check_fee_snapshot_yuan = ROUND(check_fee_snapshot / 100.0, 2) WHERE check_fee_snapshot IS NOT NULL;
ALTER TABLE repair_requests DROP COLUMN IF EXISTS check_fee_snapshot;
ALTER TABLE repair_requests RENAME COLUMN check_fee_snapshot_yuan TO check_fee_snapshot;
ALTER TABLE repair_requests ADD COLUMN IF NOT EXISTS inspection_fee_yuan decimal(10,2);
UPDATE repair_requests SET inspection_fee_yuan = ROUND(inspection_fee / 100.0, 2) WHERE inspection_fee IS NOT NULL;
ALTER TABLE repair_requests DROP COLUMN IF EXISTS inspection_fee;
ALTER TABLE repair_requests RENAME COLUMN inspection_fee_yuan TO inspection_fee;
ALTER TABLE repair_requests ADD COLUMN IF NOT EXISTS paid_amount_yuan decimal(10,2);
UPDATE repair_requests SET paid_amount_yuan = ROUND(paid_amount / 100.0, 2) WHERE paid_amount IS NOT NULL;
ALTER TABLE repair_requests DROP COLUMN IF EXISTS paid_amount;
ALTER TABLE repair_requests RENAME COLUMN paid_amount_yuan TO paid_amount;
ALTER TABLE repair_requests ADD COLUMN IF NOT EXISTS quote_amount_yuan decimal(10,2);
UPDATE repair_requests SET quote_amount_yuan = ROUND(quote_amount / 100.0, 2) WHERE quote_amount IS NOT NULL;
ALTER TABLE repair_requests DROP COLUMN IF EXISTS quote_amount;
ALTER TABLE repair_requests RENAME COLUMN quote_amount_yuan TO quote_amount;
ALTER TABLE repair_requests ADD COLUMN IF NOT EXISTS shipping_fee_yuan decimal(10,2);
UPDATE repair_requests SET shipping_fee_yuan = ROUND(shipping_fee / 100.0, 2) WHERE shipping_fee IS NOT NULL;
ALTER TABLE repair_requests DROP COLUMN IF EXISTS shipping_fee;
ALTER TABLE repair_requests RENAME COLUMN shipping_fee_yuan TO shipping_fee;
ALTER TABLE repair_transit_orders ADD COLUMN IF NOT EXISTS transit_logistics_fee_yuan decimal(10,2);
UPDATE repair_transit_orders SET transit_logistics_fee_yuan = ROUND(transit_logistics_fee / 100.0, 2) WHERE transit_logistics_fee IS NOT NULL;
ALTER TABLE repair_transit_orders DROP COLUMN IF EXISTS transit_logistics_fee;
ALTER TABLE repair_transit_orders RENAME COLUMN transit_logistics_fee_yuan TO transit_logistics_fee;
ALTER TABLE repair_transit_orders ADD COLUMN IF NOT EXISTS transit_service_fee_yuan decimal(10,2);
UPDATE repair_transit_orders SET transit_service_fee_yuan = ROUND(transit_service_fee / 100.0, 2) WHERE transit_service_fee IS NOT NULL;
ALTER TABLE repair_transit_orders DROP COLUMN IF EXISTS transit_service_fee;
ALTER TABLE repair_transit_orders RENAME COLUMN transit_service_fee_yuan TO transit_service_fee;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS actual_rent_amount_yuan decimal(10,2);
UPDATE settlements SET actual_rent_amount_yuan = ROUND(actual_rent_amount / 100.0, 2) WHERE actual_rent_amount IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS actual_rent_amount;
ALTER TABLE settlements RENAME COLUMN actual_rent_amount_yuan TO actual_rent_amount;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS cash_refundable_yuan decimal(10,2);
UPDATE settlements SET cash_refundable_yuan = ROUND(cash_refundable / 100.0, 2) WHERE cash_refundable IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS cash_refundable;
ALTER TABLE settlements RENAME COLUMN cash_refundable_yuan TO cash_refundable;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS gift_points_refunded_yuan decimal(10,2);
UPDATE settlements SET gift_points_refunded_yuan = ROUND(gift_points_refunded / 100.0, 2) WHERE gift_points_refunded IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS gift_points_refunded;
ALTER TABLE settlements RENAME COLUMN gift_points_refunded_yuan TO gift_points_refunded;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS original_rent_amount_yuan decimal(10,2);
UPDATE settlements SET original_rent_amount_yuan = ROUND(original_rent_amount / 100.0, 2) WHERE original_rent_amount IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS original_rent_amount;
ALTER TABLE settlements RENAME COLUMN original_rent_amount_yuan TO original_rent_amount;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS overdue_charges_total_yuan decimal(10,2);
UPDATE settlements SET overdue_charges_total_yuan = ROUND(overdue_charges_total / 100.0, 2) WHERE overdue_charges_total IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS overdue_charges_total;
ALTER TABLE settlements RENAME COLUMN overdue_charges_total_yuan TO overdue_charges_total;
ALTER TABLE settlements ADD COLUMN IF NOT EXISTS prepaid_refunded_yuan decimal(10,2);
UPDATE settlements SET prepaid_refunded_yuan = ROUND(prepaid_refunded / 100.0, 2) WHERE prepaid_refunded IS NOT NULL;
ALTER TABLE settlements DROP COLUMN IF EXISTS prepaid_refunded;
ALTER TABLE settlements RENAME COLUMN prepaid_refunded_yuan TO prepaid_refunded;
ALTER TABLE users ADD COLUMN IF NOT EXISTS prepaid_points_yuan decimal(10,2);
UPDATE users SET prepaid_points_yuan = ROUND(prepaid_points / 100.0, 2) WHERE prepaid_points IS NOT NULL;
ALTER TABLE users DROP COLUMN IF EXISTS prepaid_points;
ALTER TABLE users RENAME COLUMN prepaid_points_yuan TO prepaid_points;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_spending_yuan decimal(10,2);
UPDATE users SET total_spending_yuan = ROUND(total_spending / 100.0, 2) WHERE total_spending IS NOT NULL;
ALTER TABLE users DROP COLUMN IF EXISTS total_spending;
ALTER TABLE users RENAME COLUMN total_spending_yuan TO total_spending;
