ALTER TABLE users ADD COLUMN IF NOT EXISTS id_photo_other VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS real_name VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS id_card_no VARCHAR(18);
ALTER TABLE users ADD COLUMN IF NOT EXISTS face_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS face_verified_at TIMESTAMP WITH TIME ZONE;
